### ISSUE TITLE
Making Heuristic File in HeuDiConv

### ISSUE THREAD

**Issue by icetasy-dot** [brainhack-school2020/Sylvain_RestingBariatricSurgery#2]
Hi everybody

Are some of you using HeuDiConv?

I'm stuck, I was unable to create my heuristic file. I understood that i had to run a first time with no conversion for making thise file (based on this tutorial : http://www.repronim.org/coco2019-training/presentations/heudiconv/#1)

But as you can see in [https://github.com/brainhack-school2020/Sylvain_RestingBariatricSurgery/blob/master/BIDS/HeuDiConv/HeuDiConv.ipynb](url) it's not running.

Some ideas?

Thanks 

@PeerHerholz ?

**Comment by bpinsard** [comment]
The first run with convertall heuristic will generate files that you can use to generate the heuristics, but won't generate the heuristics on its own.
I can't see your notebook though.

**Comment by PeerHerholz** [comment]
Yes, please update the notebook link to the following:

https://github.com/brainhack-school2020/Sylvain_RestingBariatricSurgery/blob/master/BIDS/HeuDiConv/HeuDiConv.ipynb

You and @bpinsard are right in that you need to run it at least two times: first to get the `dicom info` that is used to create the `heuristic` and second to apply this `heuristic` to actually convert the data. Based on the output message in your notebook, I assume something went wrong with mounting the path to the data. Could you provide further information here?

**Comment by icetasy-dot** [comment]
Shure!

I know that the next step is trying to generate the heuristic form the first step, but i did get here yet... 

My Dicom are in a separate folder for each participants (folder name generate by the participant number and the date). I create a DICOM folder with a set of participant for the school. On my laptop the path is : /Users/sylvainiceta/Documents/NouveauxScan/DICOM

I put a screen shot of my folder : [https://github.com/brainhack-school2020/Sylvain_RestingBariatricSurgery/blob/master/BIDS/HeuDiConv/FolderOrganisation.png](Folder)

the bash line command I use is : 
`docker run --rm -it -v /Users/sylvainiceta/Documents/NouveauxScan/DICOM:/data:ro -v /Users/sylvainiceta/Documents/NouveauxScan/BIDS:/output nipy/heudiconv:latest \
-d /data/{subject}/{session}/*.dcm -s 'RCX219_20202020' -ss 001 -c none -f convertall -o /output`

the answer : 

> INFO: Running heudiconv version 0.8.0 latest 0.8.0
> INFO: Need to process 0 study sessions

And no file are generated
 
I also try without subject and session argument (-s and -ss) :
`docker run --rm -it -v /Users/sylvainiceta/Documents/NouveauxScan/DICOM:/data:ro -v /Users/sylvainiceta/Documents/NouveauxScan/BIDS:/output nipy/heudiconv:latest \
-d /data/{subject}/{session}/*.dcm -c none -f convertall -o /output`

The return is :

> INFO: Running heudiconv version 0.8.0 latest 0.8.0
Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv', 'console_scripts', 'heudiconv')()
  File "/src/heudiconv/heudiconv/cli/run.py", line 134, in main
    process_args(args)
  File "/src/heudiconv/heudiconv/cli/run.py", line 287, in process_args
    args.subjs, grouping=args.grouping)
  File "/src/heudiconv/heudiconv/parser.py", line 131, in get_study_sessions
    for sid in sids:
TypeError: 'NoneType' object is not iterable`

Thanks for the help!

To check if my data were not corrupted i used only dcm2niix :
 `dcm2niix /Users/sylvainiceta/Documents/NouveauxScan/DICOM/RCX219_20202020/001`

This worked and generate the nii and json file here :
[https://drive.google.com/drive/folders/12xP7-yBdB-wYt_6hWxP1YSwN_O2te5nZ?usp=sharing](url)

Thanks for the help @PeerHerholz @bpinsard

**Comment by bpinsard** [comment]
Seeing you dicom folder structure it seems that the template dicom dir should be something like

`/data/{subject}_{session}/*.dcm`

and thus the command will be like:
```docker run --rm -it -v /Users/sylvainiceta/Documents/NouveauxScan/DICOM:/data:ro -v /Users/sylvainiceta/Documents/NouveauxScan/BIDS:/output nipy/heudiconv:latest \ -d /data/{subject}_{session}/*.dcm -s 'RCX219_20202020' -ss 001 -c none -f convertall -o /output```

However, subject and session cannot contain underscore in BIDS. So you should find another naming to be BIDS valid, maybe dropping the date (which should go in metadata if you convert without fake-dates which is the default for anonymization).

**Comment by bpinsard** [comment]
Sorry, I think I misread, the date is not related  to the session!?
Do you have multiple session per subject?
So maybe something like 
```docker run --rm -it -v /Users/sylvainiceta/Documents/NouveauxScan/DICOM:/data:ro -v /Users/sylvainiceta/Documents/NouveauxScan/BIDS:/output nipy/heudiconv:latest \ -d /data/{subject}_*/*.dcm -s 'RCX219' -c none -f convertall -o /output```

**Comment by icetasy-dot** [comment]
@bpinsard

Thanks! Finally, the bug was in the *.dcm, i try with only /* that's work!
